# -*- coding: utf-8 -*-
"""24-25+psl+Allied+R1, .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XubTjx2VWWqaaGBvDfuvJ82bS-yx61h8
"""

# -*- coding: utf-8 -*-
"""25-26+psl+Allied+R1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Et0mSBaKiMdVq_5NIxWTJ2YnFb6Tnwjg
"""

!pip install pdfplumber openpyxl pandas

import pdfplumber
import pandas as pd
import re
from google.colab import files
import time

print("PDF upload karo:")
uploaded = files.upload()
pdf_filename = list(uploaded.keys())[0]

# X-axis coordinates for columns
GENDER_X = {'x0': 422.57, 'x1': 427.36}
CAT_X = {'x0': 434.97, 'x1': 456.97}
QUOTA_X = {'x0': 492.56, 'x1': 514.56}
COLLEGE_CODE_X = {'x0': 624.14, 'x1': 643.32}

def extract_column_by_coordinates(words, x0, x1, y_pos, tolerance=5):
    found_words = []
    for word in words:
        if abs(word['top'] - y_pos) > tolerance:
            continue
        if (x0 - tolerance <= word['x0'] <= x1 + tolerance) or \
           (x0 - tolerance <= word['x1'] <= x1 + tolerance):
            found_words.append(word['text'])
    return ' '.join(found_words) if found_words else ''

def is_footer_line(line):
    upper_line = line.upper().strip()
    footer_keywords = [
        'GOVERNMENT', 'STATE COMMON', 'ADMISSIONS TO',
        'PROVISIONAL', 'NOTE:', 'PRINTED ON', 'LEGENDS',
        'SR.', 'AIR', 'NEET', '---', 'NO. ROLL',
        'CAP ROUND', 'MAHARASHTRA', 'HEALTH SCIENCE',
        'LAST DATE', 'ADMITTING', 'SELECTION LIST'
    ]
    if any(upper_line.startswith(kw) for kw in footer_keywords):
        return True
    if line.count('-') > 20:
        return True
    return False

def separate_college_code_name(college_text):
    if not college_text:
        return '', ''
    if ':' in college_text:
        parts = college_text.split(':', 1)
        return parts[0].strip(), parts[1].strip()
    match = re.match(r'^(\d+)(.+)', college_text)
    if match:
        return match.group(1), match.group(2).strip()
    return '', college_text

def find_y_coordinate_for_sr_no(words, sr_no):
    for word in words:
        if word['text'] == sr_no and word['x0'] < 100:
            return word['top']
    return None

def process_page(page_num, pdf_path):
    page_data = []
    try:
        with pdfplumber.open(pdf_path) as pdf:
            page = pdf.pages[page_num - 1]

            text = page.extract_text()
            if not text:
                return page_data

            words = page.extract_words()

            sr_to_y = {}
            for word in words:
                if word['text'].isdigit() and word['x0'] < 100:
                    sr_to_y[word['text']] = word['top']

            lines = text.split('\n')

            for line in lines:
                line = line.strip()
                if not line or is_footer_line(line):
                    continue

                match = re.match(r'^\s*(\d+)\s+(\d{3,7})\s+(\d+)\s+(\d+)\s+(.+)', line)
                if not match:
                    continue

                sr_no = match.group(1)
                air = match.group(2)
                neet_roll = match.group(3)
                cet_form = match.group(4)
                rest = match.group(5).strip()

                try:
                    if int(sr_no) > 100000 or int(air) > 10000000:
                        continue
                except:
                    continue

                row_y = sr_to_y.get(sr_no)
                if not row_y:
                    row_y = find_y_coordinate_for_sr_no(words, sr_no)

                if not row_y:
                    # Fallback only for Gender, Cat, Quota, College
                    parts = rest.split()
                    gender = ''
                    category = parts[0] if len(parts) > 0 else ''
                    quota = parts[1] if len(parts) > 1 else ''
                    college_full = ' '.join(parts[2:]) if len(parts) > 2 else ''
                    college_code, college_name = separate_college_code_name(college_full)

                    page_data.append({
                        'Sr. No': sr_no,
                        'AIR': air,
                        'NEET Roll No': neet_roll,
                        'CET Form No': cet_form,
                        'Gender': '',
                        'Category': category,
                        'Quota': quota,
                        'College Code': college_code,
                        'College Name': college_name,
                        'Page': page_num,
                        'Method': 'Fallback'
                    })
                    continue

                gender = extract_column_by_coordinates(words, GENDER_X['x0'], GENDER_X['x1'], row_y)
                category = extract_column_by_coordinates(words, CAT_X['x0'], CAT_X['x1'], row_y)
                quota = extract_column_by_coordinates(words, QUOTA_X['x0'], QUOTA_X['x1'], row_y)
                college_code = extract_column_by_coordinates(words, COLLEGE_CODE_X['x0'], COLLEGE_CODE_X['x1'], row_y)

                college_words = []
                for word in words:
                    if abs(word['top'] - row_y) <= 5 and word['x0'] > COLLEGE_CODE_X['x1']:
                        college_words.append(word['text'])

                college_full = college_code + " " + " ".join(college_words)
                college_code, college_name = separate_college_code_name(college_full)

                if gender:
                    gender = gender[0] if gender[0] in ['M', 'F'] else ''

                page_data.append({
                    'Sr. No': sr_no,
                    'AIR': air,
                    'NEET Roll No': neet_roll,
                    'CET Form No': cet_form,
                    'Gender': gender,
                    'Category': category,
                    'Quota': quota,
                    'College Code': college_code,
                    'College Name': college_name,
                    'Page': page_num,
                    'Method': 'Coordinate'
                })

    except Exception as e:
        print("Error on page", page_num, ":", e)

    return page_data

print("\nProcessing...\n")

with pdfplumber.open(pdf_filename) as pdf:
    total_pages = len(pdf.pages)

all_data = []
start = time.time()

for p in range(1, total_pages + 1):
    all_data.extend(process_page(p, pdf_filename))
    if p % 5 == 0:
        print(f"Processed {p}/{total_pages} pages...")

df = pd.DataFrame(all_data)
if len(df) > 0:
    df['Sr. No'] = pd.to_numeric(df['Sr. No'], errors='coerce')
    df = df.sort_values('Sr. No').reset_index()

excel_filename = "25_26+Psl+allied+R1.xlsx"
df.drop(columns=['Method'], inplace=True)
df.to_excel(excel_filename, index=False)
files.download(excel_filename)

print("DONE ✓")

"""trying to extrat more then 93%"""



