# -*- coding: utf-8 -*-
"""24-25+psl+Ayush+R2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XubTjx2VWWqaaGBvDfuvJ82bS-yx61h8
"""

!pip install pdfplumber

import pdfplumber
import re
import pandas as pd
from google.colab import files
import gc

print("Upload PDF:")
uploaded = files.upload()
pdf_filename = list(uploaded.keys())[0]

records = []

GEN_MIN, GEN_MAX = 335, 360
CAT_MIN, CAT_MAX = 360, 430
QUOTA_MIN, QUOTA_MAX = 450, 560
CODE_MIN, CODE_MAX = 560, 620

def extract_x(words, x1, x2):
    return " ".join([w['text'] for w in words if x1 <= w['x0'] <= x2]).strip() or None

def clean_gender(g):
    if not g: return None
    g = g.strip().upper()
    if g in ["M", "MALE"]: return "M"
    if g in ["F", "FEMALE"]: return "F"
    return None

# FIRST only get total page count
with pdfplumber.open(pdf_filename) as pdf:
    total_pages = len(pdf.pages)

print("Total pages:", total_pages)

# PROCESS PAGE-BY-PAGE (RAM SAFE)
for i in range(total_pages):

    if i % 10 == 0:
        print("Processing page:", i+1)
        gc.collect()

    # OPEN PDF AGAIN → LOAD ONLY THIS PAGE
    with pdfplumber.open(pdf_filename) as temp_pdf:
        page = temp_pdf.pages[i]

        words = page.extract_words()
        words_sorted = sorted(words, key=lambda x: (round(x["top"]), x["x0"]))

    current_y = None
    line_words = []

    for w in words_sorted:
        y = round(w["top"])

        if current_y is not None and abs(y - current_y) > 2:
            wlist = line_words

            sr = None
            for t in wlist:
                if t["text"].isdigit():
                    sr = t["text"]
                    break

            nums = [t["text"] for t in wlist if re.fullmatch(r"\d{4,10}", t["text"])]

            if sr and len(nums) >= 3:
                air, roll, cet = nums[:3]

                gender = clean_gender(extract_x(wlist, GEN_MIN, GEN_MAX))
                category = extract_x(wlist, CAT_MIN, CAT_MAX)

                quota = extract_x(wlist, QUOTA_MIN, QUOTA_MAX)
                if quota:
                    quota = quota.replace("(EMD)", "").replace("(EMR)", "")
                    quota = " ".join(quota.split())

                col_raw = extract_x(wlist, CODE_MIN, CODE_MAX)
                college_code = None
                if col_raw:
                    m = re.findall(r"\b\d{4}\b", col_raw)
                    if m:
                        college_code = m[-1]

                records.append({
                    "Sr No": sr,
                    "AIR": air,
                    "Roll No": roll,
                    "CET Form No": cet,
                    "Gender": gender,
                    "Category": category,
                    "Quota": quota,
                    "College Code": college_code
                })

            line_words = []

        line_words.append(w)
        current_y = y

    del words
    del words_sorted
    gc.collect()

df = pd.DataFrame(records).drop_duplicates()
df.to_excel("25-26+psl+Ayush+R2.xlsx", index=False)
files.download("25-26+psl+Ayush+R2.xlsx")

print("\n🔥 DONE — ZERO RAM CRASH — PAGE-BY-PAGE LOADING")















