# -*- coding: utf-8 -*-
"""24-25+psl+Allied+R2,R3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ox6PjtxuHcWgiWbOkQjMqzmXoZrrhSGB
"""

!pip install pdfplumber

import pdfplumber
import re
import pandas as pd
from google.colab import files

print("Upload PDF:")
uploaded = files.upload()
pdf_filename = list(uploaded.keys())[0]

records = []

# --- FIXED COLUMN RANGES (based on your screenshot) ---
GEN_MIN, GEN_MAX = 330, 355
CAT_MIN, CAT_MAX = 355, 455
QUOTA_MIN, QUOTA_MAX = 455, 550
CODE_MIN, CODE_MAX = 550, 650

def extract_x(words, x1, x2):
    return " ".join([w['text'] for w in words if x1 <= w['x0'] <= x2]).strip() or None

def clean_gender(g):
    if not g: return None
    g = g.strip().upper()
    if g in ["M", "MALE"]: return "M"
    if g in ["F", "FEMALE"]: return "F"
    return None

with pdfplumber.open(pdf_filename) as pdf:
    for page in pdf.pages:
        words = page.extract_words()
        words_sorted = sorted(words, key=lambda x: (round(x["top"]), x["x0"]))

        current_y = None
        line_words = []

        for w in words_sorted:
            y = round(w["top"])

            # NEW LINE detected
            if current_y is not None and abs(y - current_y) > 2:
                wlist = line_words

                # -------------------------
                #       FIELD FIXES
                # -------------------------

                # SR No → 1–4 digits
                sr = None
                sr_list = [t["text"] for t in wlist if re.fullmatch(r"\d{1,4}", t["text"])]
                if sr_list:
                    sr = sr_list[0]

                # Roll No → 10–11 digits
                roll = None
                roll_list = [t["text"] for t in wlist if re.fullmatch(r"\d{10,11}", t["text"])]
                if roll_list:
                    roll = roll_list[0]

                # CET Form No → 9 digits
                cet = None
                cet_list = [t["text"] for t in wlist if re.fullmatch(r"\d{9}", t["text"])]
                if cet_list:
                    cet = cet_list[0]

                # AIR → 4–7 digits (updated)
                air = None
                air_list = [
                    t["text"]
                    for t in wlist
                    if re.fullmatch(r"\d{4,7}", t["text"])
                    and t["text"] not in (sr, roll, cet)
                ]
                if air_list:
                    air = air_list[0]

                # Only save valid rows
                if sr and air and roll and cet:
                    gender = clean_gender(extract_x(wlist, GEN_MIN, GEN_MAX))
                    category = extract_x(wlist, CAT_MIN, CAT_MAX)

                    quota = extract_x(wlist, QUOTA_MIN, QUOTA_MAX)
                    if quota:
                        quota = quota.replace("(EMD)", "").replace("(EMR)", "")
                        quota = " ".join(quota.split())

                    col_raw = extract_x(wlist, CODE_MIN, CODE_MAX)
                    college_code = None
                    if col_raw:
                        m = re.findall(r"\b\d{4}\b", col_raw)
                        if m:
                            college_code = m[-1]

                    # Append final row
                    records.append({
                        "Sr No": sr,
                        "AIR": air,
                        "Roll No": roll,
                        "CET Form No": cet,
                        "Gender": gender,
                        "Category": category,
                        "Quota": quota,
                        "College Code": college_code
                    })

                line_words = []

            line_words.append(w)
            current_y = y

df = pd.DataFrame(records).drop_duplicates()
df.to_excel("25-26+psl+allied+R3_FIXED.xlsx", index=False)
files.download("25-26+psl+allied+R3_FIXED.xlsx")

print("\n🔥 DONE — SR ✔ AIR ✔ ROLL ✔ CET ✔ Gender ✔ Category ✔ Quota ✔ College Code ✔")

